export enum ErrorCodes {
  CORPROOT_REQUIRED = 'CORPROOT_REQUIRED',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  FORBIDDEN_ORIGIN = 'FORBIDDEN_ORIGIN',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  MISSING_PARAMETER = 'MISSING_PARAMETER',
  NO_ACCESS = 'NO_ACCESS',
}
